### ISSUE TITLE
Apriori clusters check in normalization condition

### ISSUE THREAD

**Issue by asmelko** [tsieger/mhca#4]
Hi,
on line 1212 in `mhclust.c`, there is a condition that checks that not all clusters are of a Mahalanobis threshold size so the clusters can be normalized.

My question is:
Should there be a condition that checks that all samples in the apriori clusters have been clustered as well?

My reasoning behind this is that it can happen that all clusters reached Maha threshold before apriori clusters were fully clustered. And maybe? we want to normalize clusters even if we still have apriori samples?

**Comment by tsieger** [comment]
Hi, thanks for the question. 

The code is valid. The situation you are describing is unrealistic: the apriori clusters should be way smaller compared to clusters which should be treated fully in the Mahalanobis sense. IOW: `fullMahalClusterCount < clusterCount-1` should be satisfied when still forming apriori clusters. 

I've added a note at the relevant place in the code and also added a sanity check ensuring that apriori clusters are kept sufficiently small, relativelly to the `thresh` argument.
