### ISSUE TITLE
Error when installing on Mac

### ISSUE THREAD

**Issue by Close-your-eyes** [tsieger/mhca#6]
Hi, because of a recommendation I wanted to try this package and its algorithm, but unfortunately the installation failed.

Can you help or imagine what the problem may be? Thanks, Chris.

This is the error message:

** using staged installation
   ** libs
   clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c mhca-init.c -o mhca-init.o
   clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c mhclust.c -o mhclust.o
   mhclust.c:1086:120: warning: '&&' within '||' [-Wlogical-op-parentheses]
               (subthreshHandlingId==SUBTHRESHOLD_METHOD_EUCLID || subthreshHandlingId==SUBTHRESHOLD_METHOD_EUCLID_MAHAL) && wf1==1) {
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
   mhclust.c:1086:120: note: place parentheses around the '&&' expression to silence this warning
               (subthreshHandlingId==SUBTHRESHOLD_METHOD_EUCLID || subthreshHandlingId==SUBTHRESHOLD_METHOD_EUCLID_MAHAL) && wf1==1) {
                                                                                                                          ^
               (                                                                                                                   )
   1 warning generated.
   clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o mhca.so mhca-init.o mhclust.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
   ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
   ld: library not found for -lgfortran
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [mhca.so] Error 1
   ERROR: compilation failed for package ‘mhca’
─  removing ‘/private/var/folders/hd/gcy53z2x6sxd77_f8wl01by81nxlrm/T/RtmpEzmZAL/Rinst14a32da1f4d2/mhca’

**Comment by tsieger** [comment]
Hi Chris, thanks for reporting.
Unfortunately, I don't have a Mac accessible for testing, but it seems to be a problem with the `gfortran` cask on Mac: https://cynkra.com/blog/2021-03-16-gfortran-macos/. 
Could you please try if the advice given there would be of any help?
In particular, if `install.packages("cluster", type = "source")` fails, it would be a Mac-specific problem with `gfortran`. If it works, but `mhca` still fails, then it would be a `mhca`-specific problem.
Thanks.

(At least, I fixed the warning. ;-))

**Comment by Close-your-eyes** [comment]
Thanks for the fix.
On my private Mac installation was successful by the way, even though a similar error message appeared.

I will test if, with your fix, installation now works on my office-mac.

Thanks for the quick response!

**Comment by tsieger** [comment]
The warning was unrelated to the `gfortran` error, so my update won't fix it.
